spring.application.name=gestionStock

spring.datasource.url=jdbc:mysql://localhost:3306/spring_gestion_stock?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true